set shell := ["bash", "-uc"]

alias i := init
alias p := plan
alias a := apply
alias d := destroy

init:
    #!/usr/bin/env bash
    set -euo pipefail
    eval "$(uv run localstack env)"
    terraform init -backend-config=./vars/backend-config.hcl

plan:
    #!/usr/bin/env bash
    set -euo pipefail
    eval "$(uv run localstack env)"
    terraform plan -var-file=./vars/prod.tfvars

apply:
    #!/usr/bin/env bash
    set -euo pipefail
    eval "$(uv run localstack env)"
    terraform apply -var-file=./vars/prod.tfvars

destroy:
    #!/usr/bin/env bash
    set -euo pipefail
    eval "$(uv run localstack env)"
    terraform destroy -var-file=./vars/prod.tfvars
