clone:
    git clone https://github.com/minio/minio.git minio

docker_login:
    docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}" "${DOCKER_REGISTRY}"

build_minio:
    docker build --platform=linux/riscv64 -t "${DOCKER_REGISTRY}/minio" -f Dockerfile.minio ./minio

build_mc:
    docker build --platform=linux/riscv64 -t "${DOCKER_REGISTRY}/minio-mc" -f Dockerfile.mc ./minio

push: docker_login build_minio build_mc
    docker push "${DOCKER_REGISTRY}/minio"
    docker push "${DOCKER_REGISTRY}/minio-mc"
